### ISSUE TITLE
Join Files Team? or maybe MS PowerToys?

### ISSUE THREAD

**Issue by neoOpus** [GameGodS3/DropPoint#25]
Hi,

I asked [Files](https://github.com/files-community/Files) to add a similar feature then I found your solution, I was thinking about something quite similar to this and I think it would be great if many know about this get involved to make it more robust, so I suggest you to think about joining their team or maybe MS PowerToys... 

It would be amazing if you could autohide to the side of the screen feature or some similar way to remove it from view when it is not needed and get it back without having to click on systray icon or use keyboard... 

Also having a way to create several buckets (naming and pinning them optionally) ...

Enhancing this with some sort of scripting (something like [SnipDo](https://snipdo-app.com/) aka Pantherbar) so rules can be customized by power-users to automate several tasks when the files are dropped on the bucket (auto-renaming, moving, comparing, deleting etc...)

I hope it makes sense and thank you for your time and effort!

**Comment by GameGodS3** [comment]
Hey,
Thank you for your suggestions. :grin: I would love to join the communities you mentioned, and contribute meaningfully through this project. However I am unaware of how to do so. Do you have any tips on that?

**Comment by neoOpus** [comment]
Maybe by just contacting some of the developers and showing them your work! I am sure that they will take this one at least into account and who knows (it is important to try over most when you have nothing to lose)

**Comment by stefanmm** [comment]
Definitely try with MS PowerToys, I am sure they will want this! This is a GREAT feature that I wanted for so many years, and I am sure there are many users like me. Go all in, this is huge :)
