### ISSUE TITLE
Unable to open DropPoint for 14 inch M1 Macbook Pro + Monterey 12.5.1

### ISSUE THREAD

**Issue by DaddyF** [GameGodS3/DropPoint#28]
**Describe the bug**
Cannot open the DropPoint after Open "System Preferences > Security & Privacy > Open Anyway"

**To Reproduce**
1. Select the DropPoint in Application.
2. Open it and get error to move it to trash.

**Expected behavior**
just open it.

**Screenshots**
Please see attached.

**Desktop (please complete the following information):**
 - OS: 
 - macOS Monterey
Version 12.5.1
MacBook Pro (14-inch, 2021)
Chip Apple M1 Pro
Memory 16 GB
Startup Disk Macintosh HD
 - DropPoint Version
 - DropPoint-1.2.0-arm64-Apple-Silicon.dmg (for Apple M1 devices only)

**Additional context**
no
[DropPoint.docx](https://github.com/GameGodS3/DropPoint/files/9438946/DropPoint.docx)

**Comment by GameGodS3** [comment]
Hello,
I have updated the arm64 DMG file in the releases. Could you download and try running the new release? Do let us know if there's any problems.

**Comment by DaddyF** [comment]
I have downloaded the one which is created 5 hours ago. But the result is the same. Is there any more information that I should give? Have you tested on your side and did it work? 
[Doc1.docx](https://github.com/GameGodS3/DropPoint/files/9451861/Doc1.docx)

**Comment by DaddyF** [comment]
Hi

I have downloaded the one and tried to open it. But I got an error as before. So I cannot do any more test from here.
Have you tested on 14” M1 Macbook pro? If so, then there could be something I can test more. If not, I will wait further information.

Best regards,
Sadao Fukatsu

**Comment by AJAYK-01** [comment]
Hey, could you run ```xattr -cr /Applications/DropPoint.app``` in your terminal after installing the app and update if it works. Seems to be some issue with signing, as I don't have a developer account.

**Comment by DaddyF** [comment]
It worked.
~ $ xattr -l /Applications/DropPoint.app 
com.apple.quarantine: 0181;630e7226;Microsoft\x20Edge;BA24E331-0480-4EE5-8DCA-A36842220D21
 ~ $ xattr -cr /Applications/DropPoint.app 
 ~ $ xattr -l /Applications/DropPoint.app 

Is there a keyboard shortcut to call the DropPoint? It would help if it will open it near the current cursor.

**Comment by AJAYK-01** [comment]
> It worked. ~ $ xattr -l /Applications/DropPoint.app com.apple.quarantine: 0181;630e7226;Microsoft\x20Edge;BA24E331-0480-4EE5-8DCA-A36842220D21 ~ $ xattr -cr /Applications/DropPoint.app ~ $ xattr -l /Applications/DropPoint.app
> 
> Is there a keyboard shortcut to call the DropPoint? It would help if it will open it near the current cursor.

The app should be kept running in the background without Cmd+Q quitting. Then it will open new instance to every ```Shift+Tab```

**Comment by DaddyF** [comment]
Thank you. It worked. This is very nice.
