### ISSUE TITLE
files with .numbers, .pages, .key do not work on 14" Macbook pro

### ISSUE THREAD

**Issue by DaddyF** [GameGodS3/DropPoint#29]
**Describe the bug**
files such as .pages will not be copied to DropPoint

**To Reproduce**
1. type shift+tab
2. drag xx.pages to the DropPoint
3. the Icon on the DropPoint will not change. So there is no files to move out.

**Expected behavior**
File icon will be shown on the DropPoint

**Screenshots**

**Desktop (please complete the following information):**
 - macOS Monterey
Version 12.5.1
MacBook Pro (14-inch, 2021)
Chip Apple M1 Pro
Memory 16 GB
 - DropPoint-1.2.0-arm64-Apple-Silicon. dm (for Apple M1 devices only)

**Additional context**
.m4a, .csv, .pdf, .doc, .docx, .pptx, .xlsx, .xlsm worked fine.
[This example will not work.docx](https://github.com/GameGodS3/DropPoint/files/9466766/This.example.will.not.work.docx)

**Comment by AJAYK-01** [comment]
> **Describe the bug** files such as .pages will not be copied to DropPoint
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. type shift+tab
> 2. drag xx.pages to the DropPoint
> 3. the Icon on the DropPoint will not change. So there is no files to move out.
> 
> **Expected behavior** File icon will be shown on the DropPoint
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * macOS Monterey
>   Version 12.5.1
>   MacBook Pro (14-inch, 2021)
>   Chip Apple M1 Pro
>   Memory 16 GB
> * DropPoint-1.2.0-arm64-Apple-Silicon. dm (for Apple M1 devices only)
> 
> **Additional context** .m4a, .csv, .pdf, .doc, .docx, .pptx, .xlsx, .xlsm worked fine. [This example will not work.docx](https://github.com/GameGodS3/DropPoint/files/9466766/This.example.will.not.work.docx)

This issue seems to be solved in the latest release, could you check if the issue persists @DaddyF ?

**Comment by DaddyF** [comment]
1.2.1 seems to work fine. I have tested the followings.
folders, .pages, .numbers, .key, .zip, .pdf, dmg, .ppt, .m4a, .xls, .xlsm, .csv, .numbers
Thank you very much for the fix.
