### ISSUE TITLE
Dragging out not working, the files gets cleared when trying to drag out in Ubuntu 20.04

### ISSUE THREAD

**Issue by rawho** [GameGodS3/DropPoint#3]
Dragging in is working fine. 
When gone to the desired location and while trying to drag it out, the files get cleared. 
- OS: Ubuntu 20.04 
- DropPoint Version: v1.0.0
See the issue recorded here:
https://www.loom.com/share/d1852f8f829849ef9201db36de439626

**Comment by GameGodS3** [comment]
Could you also tell me the method by which you installed DropPoint? deb, appimage or npm?

**Comment by AJAYK-01** [comment]
> Could you also tell me the method by which you installed DropPoint? deb, appimage or npm?

Both appimage and deb seem to have this issue when I tried on ubuntu

**Comment by GameGodS3** [comment]
Issue has been fixed. Updated release will be deployed soon. Thanks!
