### ISSUE TITLE
In full screen mode, DropPoint will appear in another space

### ISSUE THREAD

**Issue by DaddyF** [GameGodS3/DropPoint#30]
**Describe the bug**
It seems that the DropPoint will not appear in the same screen in full screen mode.

**To Reproduce**
0. open finder with a new window
1. Click the left upper side green button to make the window full-screen mode
2. type shift-tab
3. screen will be changed to a new space and the DropPoint will appear there.
4. no way to use the original finder

**Expected behavior**
even if in the full screen mode, DropPoint should appear in the original full-screen window

**Screenshots**
it should be clear if follow the above steps

**Desktop (please complete the following information):**
macos Monterey
Version 12.5.1
MacBook Pro (14-inch, 2021)
Chip Apple M1 Pro
Memory 16 GB

**Additional context**
If this is done in an external display, the DropPoint will appear in the macbook main display, but it would be better to let it appear in the same windows. I guess this issue is the macOS spec and cannot avoid it. So better use it not in a full-screen mode.

**Comment by AJAYK-01** [comment]
Full screen mode support is not available as of now, but is on the list for future updates.

**Comment by AJAYK-01** [comment]
Hey @DaddyF the issue has been fixed in my fork now.

You may try the new build [here](https://github.com/AJAYK-01/DropPoint/releases/tag/v1.2.1)

**Comment by DaddyF** [comment]
As long as I am using the DropPoint on my Macbook screen, it works. When I do it in an external display, the DropPoint appears in my Macbook screen.

**Comment by AJAYK-01** [comment]
> As long as I am using the DropPoint on my Macbook screen, it works. When I do it in an external display, the DropPoint appears in my Macbook screen.

This is a known issue #8 which would require some significant updates.
